---
- name: Create AppConfig instance.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Read the variables from var file
      include_vars:
        file: vars.yml
    - name: Create a AppConfig instance
      ibm_resource_instance:
        name: "{{ instance_name }}"
        service: "apprapp"
        plan: "{{ plan_type }}"
        location: "{{ location_info }}"
